[libraries.python3.vm] Fix capstone
Replace `capstone-windows` by `capstone` as the `capstone-windows`
library was last updated in 2015 and importing it failed with the
following error:
```
PS C:\Users\flare > python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import capstone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\site-packages\capstone\__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```

The `capstone` library seems to be working fine:
```
PS C:\Users\flare > python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import capstone
>>> print(capstone.__version__)
5.0.6
>>>
>>> from capstone import *
>>>
>>> CODE = b"\x55\x48\x8b\x05\xb8\x13\x00\x00"
>>>
>>> md = Cs(CS_ARCH_X86, CS_MODE_64)
>>> for i in md.disasm(CODE, 0x1000):
...     print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
...
0x1000: push    rbp
0x1001: mov     rax, qword ptr [rip + 0x13b8]
```